### ISSUE TITLE
ImportError: cannot import name 'string_int_label_map_pb2' from 'object_detection.protos' 

### ISSUE THREAD

**Issue by ykslchua** [nicknochnack/TFODCourse#12]
Thanks for sharing this amazing tutorial Nicholas.
 
**I ran :**
!python {files['TF_RECORD_SCRIPT']} -x {os.path.join(paths['IMAGE_PATH'], 'train')} -l {files['LABELMAP']} -o {os.path.join(paths['ANNOTATION_PATH'], 'train.record')} 
!python {files['TF_RECORD_SCRIPT']} -x {os.path.join(paths['IMAGE_PATH'], 'test')} -l {files['LABELMAP']} -o {os.path.join(paths['ANNOTATION_PATH'], 'test.record')} 

**and got :**
Traceback (most recent call last):
  File "C:\NRenotte\Tensorflow\scripts\generate_tfrecord.py", line 29, in <module>
    from object_detection.utils import dataset_util, label_map_util
  File "C:\Users\cyukiat\AppData\Local\Programs\Python\Python39\lib\site-packages\object_detection\utils\label_map_util.py", line 21, in <module>
    from object_detection.protos import string_int_label_map_pb2
ImportError: cannot import name 'string_int_label_map_pb2' from 'object_detection.protos' (C:\Users\cyukiat\AppData\Local\Programs\Python\Python39\lib\site-packages\object_detection\protos\__init__.py)
Traceback (most recent call last):
  File "C:\NRenotte\Tensorflow\scripts\generate_tfrecord.py", line 29, in <module>
    from object_detection.utils import dataset_util, label_map_util
  File "C:\Users\cyukiat\AppData\Local\Programs\Python\Python39\lib\site-packages\object_detection\utils\label_map_util.py", line 21, in <module>
    from object_detection.protos import string_int_label_map_pb2
ImportError: cannot import name 'string_int_label_map_pb2' from 'object_detection.protos' (C:\Users\cyukiat\AppData\Local\Programs\Python\Python39\lib\site-packages\object_detection\protos\__init__.py)

**I have tried unsuccessfully :**
!from tensorflow/models/research/
protoc object_detection/protos/*.proto --python_out=.

export PYTHONPATH=$PYTHONPATH:pwd:pwd/slim

**Sorry I am new to this...**
![Error](https://user-images.githubusercontent.com/86035172/123354031-5fdb8f00-d595-11eb-8fe5-0c044d66c337.PNG)

**Comment by WhenPigsInvade** [comment]
Hello, did you ever manage to fix this issue? And if so do you mind sharing your steps?

**Comment by WhenPigsInvade** [comment]
> Hello, did you ever manage to fix this issue? And if so do you mind sharing your steps?

Oh I figured this out, hopefully this helps someone else. You have to install the correct object_detection package on pip.

I ran ``pip install object-detection-0.1`` and the error was fixed.
