### ISSUE TITLE
GeneratorDatasetOp::Dataset will not be optimized because the dataset does not implement the AsGraphDefInternal() method needed to apply optimizations.

### ISSUE THREAD

**Issue by Yozor4** [nicknochnack/TFODCourse#125]
I started training but it is showing this line, the training is not working because of this

![image](https://user-images.githubusercontent.com/99131482/216349618-ceded565-4e6c-41ab-a55f-0997b9268f7d.png)

**Comment by ASH-will-WIN** [comment]
I am having the same problem

**Comment by Yozor4** [comment]
I found that my generated TFRecord files were empty, due to putting my train and test folders containing the XML files in the incorrect folder. After fixing the issue by placing the folders in the correct location, I successfully created the TFRecord files. The training is functioning properly now.

**Comment by Yozor4** [comment]
try to check your generated tf record files

**Comment by ASH-will-WIN** [comment]
Ok, Thank you.

**Comment by banteng56** [comment]
Sorry, can you explain in more detail what the empty folder is? and what file must it be filled in?
