### ISSUE TITLE
Error while installing pycocotools

### ISSUE THREAD

**Issue by kamtafw** [nicknochnack/TFODCourse#46]
ERROR: Failed building wheel for pycocotools

**Comment by longqua69** [comment]
Hi @tiva-0007 ,

I have the same issue as you. Many people try this approach [Resolved pycocotools](https://github.com/philferriere/cocoapi). Please take a look

**Comment by longqua69** [comment]
@tiva-0007 ,

I've added a solution to fix this issue. See whether or not #52  can fix the issue from your end

**Comment by kamtafw** [comment]
Thanks for your suggestions everyone. I was able to fix the issue some days back.
I reinstalled my VS build tools and there were no more errors.
